### ISSUE TITLE
Service can't be launched (status 217) 

### ISSUE THREAD

**Issue by djipca** [nvtkaszpir/prusa-connect-camera-script#1]
I have a C270 HD webcam on /dev/video0
I can launch the prusaconnect script but can't lauch the service.

`jp@rasp1:/home/pi/src/prusa-connect-camera-script $ systemctl status prusa-connect-camera@env.service
● prusa-connect-camera@env.service - Prusa Connect Camera Script
     Loaded: loaded (/etc/systemd/system/prusa-connect-camera@.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Mon 2024-05-06 23:08:09 EDT; 17min ago
    Process: 853 ExecStart=/home/pi/src/prusa-connect-camera-script/prusa-connect-camera.sh (code=exited, status=217/USER)
   Main PID: 853 (code=exited, status=217/USER)
        CPU: 0

May 06 23:08:09 rasp1 systemd[1]: prusa-connect-camera@env.service: Scheduled restart job, restart counter is at 5.
May 06 23:08:09 rasp1 systemd[1]: Stopped Prusa Connect Camera Script.
May 06 23:08:09 rasp1 systemd[1]: prusa-connect-camera@env.service: Start request repeated too quickly.
May 06 23:08:09 rasp1 systemd[1]: prusa-connect-camera@env.service: Failed with result 'exit-code'.
May 06 23:08:09 rasp1 systemd[1]: Failed to start Prusa Connect Camera Script.
jp@rasp1:/home/pi/src/prusa-connect-camera-script $ ./prusa-connect-camera.sh 
Using fswebcam
Camera capture command: fswebcam -d /dev/video0 --resolution 1280x720 --no-banner /dev/shm/camera_178d2836-3e20-4068-a889-024ab4e6d3ec.jpg
Starting camera loop...
{"status_code":204}200
{"status_code":204}200`

![Image_2024-05-06_23_27_collée](https://github.com/nvtkaszpir/prusa-connect-camera-script/assets/105440633/a41d91e2-3123-4b40-9149-81ae3dcf9a3a)

Thanks for helping, I think I'm close to get it working. 

---
other details
Working on PrusaLink not on connect.
I have to kill the user to make it work on connect, without seeing images on connect.prusa...
<img width="539" alt="image" src="https://github.com/nvtkaszpir/prusa-connect-camera-script/assets/105440633/950a6a53-db57-4039-a1a3-0fc9ed154a9c">

I'll check this link 
https://forum.prusa3d.com/forum/introcuctions-instrutctions/camera-not-visible-on-prusa-connect-but-working-on-prusa-link/

**Comment by nvtkaszpir** [comment]
1. More details how to see the error:

Open one terminal and type in
```shell
systemctl stop connect-camera@env.service
sudo journalctl -f -u prusa-connect-camera
```

Then open another terminal and type
```shell
systemctl start prusa-connect-camera@env.service
sleep 5
systemctl stop connect-camera@env.service
```
This should run service once and then in the first terminal you should see the whole output why the script fails.
Then paste the output in the github in the code block - please wrap code or logs in triple backtick blocks https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

2. I suspect different permissions issues because you run script as user `jp` while the systemd service has hardcoded user `pi`.

 I see you run the script as user `jp`, and this user is able to use `/dev/video0` and also creates a file in `/dev/shm/camera_*`
Next, if you stop the script and run the systemd service then it will run as different user - actually as `pi` because that is what I hardcoded in the systemd unit file (assuming `pi` user is a default account on the system`.

So you have few options how to solve it:

- delete files  `/dev/shm/camera_*` and start the systemd service again, so that user `pi` will be able to create and write to that file. Also you can check if the user `pi` is the in the video group so that there are no issues with accessing `/dev/vide0` (I assme it already is, you can check it with `sudo groups pi`)

- change `/etc/systemd/system/prusa-connect-camera@.service` file  via `sudo nano /etc/systemd/system/prusa-connect-camera@.service` and replace `User=pi` and `Group=pi` with the current user and group so it is `User=jp` and `Group=jp`, then do `sudo systemctl daemon-reload` and start service again - this way it will use your user account to access camera device and write files.

3. running PrusaLink and this script on the same device and accessing the same camera is not supported, because the first started app takes over the control of the camera device and other apps cannot use it.
So if you start PrusaLink then my script will not work. If you start my script first, then image in PrusaLink will not work.

Also maybe you need to update PrusaLink to support using `Content-Length` header that is now required.
But in general this is a PrusaLink sending to PrusaConnect issue.

I don't know the details of the internals how PrusaLink is accessing the camera, but there may be an option to create virtual camera stream loopback devices so that PrusaLink uses one and my camera uses another device, but this is not that easy to set up.

**Comment by djipca** [comment]
Thanks for the answer, I'll check that up and get you a feedback (I have stuff printing, that I can't interrupt. )

**Comment by nvtkaszpir** [comment]
any progress on this? if not I'll close it in about 1 month
