### ISSUE TITLE
prusa-connect-camera-script fails using systemctl

### ISSUE THREAD

**Issue by EZWoodworker** [nvtkaszpir/prusa-connect-camera-script#2]
I get the following:

$ sudo systemctl enable prusa-connect-camera@env.service
sudo systemctl start prusa-connect-camera@env.service
sudo systemctl status prusa-connect-camera@env.service
Job for prusa-connect-camera@env.service failed because of unavailable resources or another system error.
See "systemctl status prusa-connect-camera@env.service" and "journalctl -xeu prusa-connect-camera@env.service" for details.
● prusa-connect-camera@env.service - Prusa Connect Camera Script
     Loaded: loaded (/etc/systemd/system/prusa-connect-camera@.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: resources) since Wed 2024-06-05 10:47:16 EDT; 39ms ago
        CPU: 0

**Comment by nvtkaszpir** [comment]
please provide more log details, see https://nvtkaszpir.github.io/prusa-connect-camera-script/troubleshooting/#systemd-troubleshooting

**Comment by EZWoodworker** [comment]
Nothing ever appears in the journal.
It runs perfectly when doing the test config.  
Apparently, the service is taking hold of the camera as I have to stop the service before I can do the test config.

**Comment by nvtkaszpir** [comment]
yeah, you must stop the service to run the test config or vice versa (stop test config to run the service) especially if you use direct hardware (csi/usb cams).

I guess you may have issues with the permissions to access files? AFAIR running test config (especially with sudo) will require deleting or changing permissions to the created files (see /dev/shm/ dir and change owner/delete files)
Also sudo journalctl should be able to provide logs for the service.

One more thing, `Active: activating (auto-restart) (Result: resources) since Wed 2024-06-05 10:47:16 EDT; 39ms ago` may meany that there is an issue with the target config used in the unit file or maybe lack of other resources to run additional service. Make sure you have a file `/home/pi/src/prusa-connect-camera-script/.env`

Can you provide more details about the config and hardware/software details?

**Comment by EZWoodworker** [comment]
Solved.
I don't know if I missed it, but the "prusa-connect-camera@.service" had to be edited to have my location of the script and ".env" files.
